[pytest]

log_cli = true
log_cli_level = INFO

log_file = logs/automation.log
log_file_level = INFO

log_file_format = %(asctime)s | %(levelname)s | %(message)s
log_file_date_format = %H:%M:%S

addopts =
    -v
    --html=reports/report.html
    --self-contained-html

markers =
    e2e: End to End test cases
    positive: marks tests that are expected to succeed
    negative: marks tests that are expected to fail or invalid input
